package AdditionApp;


/**
* AdditionApp/AdditionOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Addition.idl
* Tuesday, April 7, 2015 11:04:19 PM IST
*/

public interface AdditionOperations 
{
  int add (int a, int b);
  String otherClientStatus ();
  void shutdown ();
} // interface AdditionOperations
